FROM python:3.8-alpine3.11

EXPOSE 8000

WORKDIR /Nokia

COPY poetry.lock pyproject.toml ./

RUN pip3 install poetry && \
    poetry config virtualenvs.create false && \
    poetry install

COPY ./src ./src

ENTRYPOINT ["poetry"]
CMD["run","task","dev-server"]